name: datawhys
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - jupyterlab=4.1.8
  - ca-certificates
  - openssl
  - nodejs=20
  - git
  - copier=9
  - jinja2-time
  - certifi
  - jupyter-lsp-python
  - jupyterlab-lsp
  - scikit-learn=1.4.2
  - anywidget
  - plotly=5.22.0
  - pandas=2.2.2
  - pip
  - jedi=0.18.1 
  - numpy
  - statsmodels
  - pygraphviz
  - python-graphviz
  - seaborn 
    
